name: Code Signing

on:
  push: 
    branches: master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.18.1
      - name: Install NPM packages
        run: npm install

      - name: Code Signing
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CODESIGN }}'
          folder: 'files'
          recursive: true

      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/angular-githubaction/*"
          token: ${{ secrets.TOKEN }}
        
